steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Use Terraform 0.11.11'
  inputs:
    terraformVersion: 0.11.11

- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: 'terraform.tfvars'

- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: 'backend.tfvars'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.SourcesDirectory)'
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    targetFolder: $(Build.SourcesDirectory)

- script: 'terraform init -backend-config="backend.tfvars"'
  displayName: 'Terraform init'

- script: 'terraform apply -auto-approve'
  displayName: 'Terraform apply'

- task: AzurePowerShell@3
  displayName: 'Update StreamAnalytics with Powershell'
  inputs:
    azureSubscription: $(subscription)
    scriptType: 'FilePath'
    scriptPath: './StreamAnalytics/Update-StreamAnalyticsIOQueries.ps1'
    errorActionPreference: 'stop'
    failOnStandardError: false
    azurePowerShellVersion: 'latestVersion'
    

- task: DeleteFiles@1
  displayName: 'Delete files from $(Build.SourcesDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'