trigger:
- master
- features/*
- feature/*

steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Use Terraform 0.11.11'
  inputs:
    terraformVersion: 0.11.11

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 

- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: 'terraform.tfvars'

- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: 'backend.tfvars'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.SourcesDirectory)'
  inputs:
    sourceFolder: $(Agent.TempDirectory)
    targetFolder: $(Build.SourcesDirectory)

- script: 'terraform init -backend-config="backend.tfvars"'
  displayName: 'Terraform init'

- script: 'terraform plan'
  displayName: 'Terraform plan'    

steps:
- task: CopyFiles@2
  displayName: 'Copy Terraform files to artifacts'
  inputs:
    SourceFolder: Terraform
    TargetFolder: '$(build.artifactstagingdirectory)/Terraform'

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: DeleteFiles@1
  displayName: 'Delete files from $(Build.SourcesDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'